spring.application.name=demo34

logging.level.root=INFO
logging.level.com.example.demo.controller=TRACE
logging.file.name=logs/application.log

server.error.include-exception=true
server.error.include-message=always